server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      force-response: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/  #? ???? ??? ?? ?????? /WEB-INF/views/? ????
      suffix: .jsp  #? ?? ?? ?? ???? .jsp? ????

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=Asia/Seoul
    username: jang   #???????? ?????? cos???
    password: 8941  #?????? ?? ????? cos1234? ??